### PR TITLE
Update code

### PR DESCRIPTION
**Pull request by walkerbry453**

### CODE REVIEW

**Review by wherrickjr1 — APPROVED** [review]
looks good to me

**Review by brussell23 — APPROVED** [review]
Good change, 100 is too long

**Review by TEA-Jon-Armst — COMMENTED** [review]
I'm Jonathan Armstrong and I approve this message.

**Review by ChrisHartig44 — APPROVED** [review]

**Review by sfranklintea — APPROVED** [review]
Approved!

**Comment by noorahalhasan** [comment]
Delete lines 16 and 17

**Pull request merged**
